### ISSUE TITLE
main.py doesnt open

### ISSUE THREAD

**Issue by MikeTHEPro** [Poseidown/fusion-files#1]
![image](https://user-images.githubusercontent.com/36313151/48131479-dc13ed80-e298-11e8-98f9-4ee02927be12.png)

**Comment by Poseidown** [comment]
You are missing a dependency. In the README.md you can see all that are required. The one this error suggests that you are missing is Crypto. You can get it through a command prompt with the following command:
pip install pycrypto

**Comment by MikeTHEPro** [comment]
when i installed it i got this error
![image](https://user-images.githubusercontent.com/36313151/48156788-c9b8a480-e2d6-11e8-8190-d04b46465e22.png)

but after getting this installed
https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

I got another error
![image](https://user-images.githubusercontent.com/36313151/48157160-94f91d00-e2d7-11e8-9f08-9225597a0006.png)
even though:
![image](https://user-images.githubusercontent.com/36313151/48157257-d12c7d80-e2d7-11e8-980d-8317285a7e81.png)

**Comment by MikeTHEPro** [comment]
How do I do that

Στις Πέμ, 8 Νοε 2018, 8:24 μ.μ. ο χρήστης PoseidOwn <
notifications@github.com> έγραψε:
